name: Build and deploy to docs folder on main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Commit and push docs folder if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "Update docs folder with latest build [skip ci]"
            git push origin main
          else
            echo "No changes in docs folder"
          fi